language: java
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
deploy:
  provider: releases
  api_key:
    secure: job0XnXHrUE7e9yxUyGneXDjylDiOdZgzaTHELF1tesZUaFVtaOLtNxSHH1pmeylHVf6bgbngZzOusZllC4sZ/91YouhCm32J6aet1AQYfMGAjN0GMWDLAWoXDKHyingfTWHy7vToehWvUb++m8d3HTczjkqh+ktb+w409VcbwA=
  file: build/libs/rundeck-s3-log-plugin-*.jar
  file_glob: true
  on:
    tags: true
